### ISSUE TITLE
Importing scanpro with error

### ISSUE THREAD

**Issue by NarainritKaruna** [loosolab/scanpro#1]
Hi,

I try to import scanpro, but there are some issues with DLL files even installed visual C+.
###################################################################
ImportError                               Traceback (most recent call last)
Cell In[2], line 4
      2 import anndata as ad
      3 import numpy as np
----> 4 from scanpro import scanpro, anova, t_test
      5 from scanpro.linear_model import create_design
      6 from scanpro.get_transformed_props import get_transformed_props

File ~\anaconda3\Lib\site-packages\scanpro\__init__.py:17
     14 module_name = ".".join(c.split(".")[:-1])
     15 attribute_name = c.split(".")[-1]
---> 17 module = import_module(module_name)
     18 attribute = getattr(module, attribute_name)
     20 globals()[attribute_name] = attribute

File ~\anaconda3\Lib\importlib\__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File ~\anaconda3\Lib\site-packages\scanpro\scanpro.py:8
      5 from statsmodels.stats.multitest import multipletests
      6 from statsmodels.tools.tools import add_constant
----> 8 from scanpro.get_transformed_props import get_transformed_props
      9 from scanpro.linear_model import lm_fit, contrasts_fit, create_design
     10 from scanpro import ebayes

File ~\anaconda3\Lib\site-packages\scanpro\get_transformed_props.py:3
      1 import numpy as np
      2 import pandas as pd
----> 3 from scanpro.utils import norm_counts
      6 def get_transformed_props(data, sample_col='sample', cluster_col='cluster', transform='logit'):
      7     """Calculate and normalize proportions using logit or arcsin transformation.
      8 
      9     :param [pandas.DataFrame, anndata.AnnData] data: Anndata object or pandas dataframe containing single-cell data.
   (...)
     12     transformed proportions, respectively.
     13     """

File ~\anaconda3\Lib\site-packages\scanpro\utils.py:7
      4 import pandas as pd
      5 from scipy.stats import binom, nbinom
----> 7 from scanpro import gaussq2
     10 def del_index(x, indices):
     11     """Delete rows and columns of a 1 or 2D numpy array based on indices.
     12 
     13     :param numpy.ndarray x: Numpy array.
     14     :param list indices: List of indices.
     15     :return numpy.ndarray: Sliced array.
     16     """

ImportError: DLL load failed while importing gaussq2: The specified module could not be found.
#################################################################################
Do you have any suggestion?

Best regards,

**Comment by yalayoubi** [comment]
Hello,
sorry for the late response. 
hmm that's weird, are you on windows or a linux machine? you could try to install the scanpro_analysis conda environment and see if you get the same error, you can find the installation steps here:
`https://github.com/loosolab/scanpro/tree/main/Alayoubi_et_al_2023`

**Comment by yalayoubi** [comment]
closing since gaussq2 is now implemented in python instead of fortran, the import error should be fixed
