### ISSUE TITLE
Unable to install "scanpro" successfully

### ISSUE THREAD

**Issue by yingxuexiao** [loosolab/scanpro#3]
Hi~
I recently discovered your fascinating "scanpro" method and I am eager to explore its capabilities. However, I have encountered difficulties during the installation process.

I followed your instructions diligently, creating a Conda environment as specified：
`xiaoying@yingxueMacBook-Air scanpro % conda create -n scanpro_analysis python=3.9 matplotlib=3.7.1 ipykernel ipywidgets`

Despite my efforts, I consistently encounter issues when attempting to install the package. The error message I receive is ：
```
Building wheel for scanpro (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [200 lines of output]
      /private/var/folders/mz/b7xw87zx6x14klwrssv2k7l40000gn/T/pip-install-8rx594_6/scanpro_af9750597c3642af92fb034cc0e6c8c3/setup.py:8: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
```

```
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scanpro
  Running setup.py clean for scanpro
Failed to build scanpro
ERROR: Could not build wheels for scanpro, which is required to install pyproject.toml-based projects
```

I would greatly appreciate any guidance or suggestions you could provide to help resolve this matter. Your expertise and assistance would be invaluable to me in getting "scanpro" up and running successfully.

Thank you very much for your time and consideration. I eagerly await your response.

Best regards,
yingxuexiao

**Comment by yalayoubi** [comment]
Hi @yingxuexiao 
thank you for reporting this. I did not have this problem when creating the environment and installing scanpro from pip `pip install scanpro`. The deprecation of distutils should not be a problem as long as you have a python version `,=3.11`. Can you please provide more context to how you tried to install it?

**Comment by yingxuexiao** [comment]
> Hi @yingxuexiao thank you for reporting this. I did not have this problem when creating the environment and installing scanpro from pypi `pip install scanpro`. The deprecation of distutils should not be a problem as long as you have a python version `<=3.11`. Can you please provide more context to how you tried to install it?

Hello,
I've had issues with this before, but I was successful when I tried again today. Thank you very much for your assistance!
Best regards,
yingxuexiao
